"""Add is_admin

Revision ID: 37642520cc44
Revises: 3a1013086d2c
Create Date: 2026-04-11 23:40:21.406581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37642520cc44'
down_revision = '3a1013086d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
