"""add player fields

Revision ID: 41148f0d7f9f
Revises: f6ebb13bf378
Create Date: 2026-04-12 00:15:30.969373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41148f0d7f9f'
down_revision = 'f6ebb13bf378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matchday', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pda_goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atg_goals', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('playing_now', sa.Boolean(), nullable=True))
        batch_op.drop_column('team_a_goals')
        batch_op.drop_column('team_b_goals')

    with op.batch_alter_table('match_assignment', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=3),
               existing_nullable=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_goalkeeper', sa.Boolean(), nullable=True))
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('is_goalkeeper')

    with op.batch_alter_table('match_assignment', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_b_goals', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('team_a_goals', sa.INTEGER(), nullable=True))
        batch_op.drop_column('playing_now')
        batch_op.drop_column('atg_goals')
        batch_op.drop_column('pda_goals')
        batch_op.drop_column('cost')
        batch_op.drop_column('location')
        batch_op.drop_column('matchday')

    # ### end Alembic commands ###
