"""add_kit_colors

Revision ID: ae47e90660f3
Revises: fd19ae4d0080
Create Date: 2026-04-12 01:59:50.811580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae47e90660f3'
down_revision = 'fd19ae4d0080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pda_kit_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('atg_kit_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('atg_kit_color')
        batch_op.drop_column('pda_kit_color')

    # ### end Alembic commands ###
