"""Add player details and match mvp

Revision ID: c9461e0a9d18
Revises: 41148f0d7f9f
Create Date: 2026-04-12 01:08:24.390634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9461e0a9d18'
down_revision = '41148f0d7f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mvp_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_match_mvp_id', 'player', ['mvp_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('jersey_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('jersey_number')
        batch_op.drop_column('birth_date')

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mvp_id')

    # ### end Alembic commands ###
