"""Replace is_goalkeeper with position in Player model

Revision ID: f6ebb13bf378
Revises: 37642520cc44
Create Date: 2026-04-11 23:43:03.006700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ebb13bf378'
down_revision = '37642520cc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=20), nullable=True))
        batch_op.drop_column('is_goalkeeper')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_goalkeeper', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('position')

    # ### end Alembic commands ###
